- name: Configure MERN App Server
  hosts: app
  become: true

  tasks:
    - name: Install Node.js and npm
      yum:
        name: nodejs
        state: present

    - name: Install git
      yum:
        name: git
        state: present

    - name: Clone TravelMemory repo
      git:
        repo: https://github.com/UnpredictablePrashant/TravelMemory
        dest: /home/ec2-user/TravelMemory
        version: main

    - name: Install backend dependencies
      shell: |
        cd /home/ec2-user/TravelMemory/backend
        npm install

    - name: Install frontend dependencies
      shell: |
        cd /home/ec2-user/TravelMemory/frontend
        npm install

    - name: Create .env file
      copy:
        dest: /home/ec2-user/TravelMemory/backend/.env
        content: |
          MONGO_URI=mongodb://DB_SERVER_PRIVATE_IP:27017/travelmemories
          PORT=5000

    - name: Start backend
      shell: |
        cd /home/ec2-user/TravelMemory/backend
        nohup npm start &

    - name: Start frontend
      shell: |
        cd /home/ec2-user/TravelMemory/frontend
        nohup npm start &